name: Update Aggregated Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: true
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install || echo "No dependencies needed"

      - name: 1. Generate Aggregated Data
        run: node scripts/1_generate-mapped-data.js

      - name: 2. Generate Dua from Al-Qur'an
        run: node scripts/2_generate-dua-from-al-quran.js

      - name: 3. Generate Dua from As-Sunnah
        run: node scripts/3_generate-dua-from-as-sunnah.js

      - name: 4. Generate Tokenized Categories
        run: node scripts/4_generate-tokenized-categories.js

      - name: 5. Generate Tokenized Categories Sorted by Most Count
        run: node scripts/5_generate-tokenized-categories-sorted-by-most-count.js

      - name: 6. Generate Dua of the Prophets
        run: node scripts/6_generate-dua-of-the-prophets.js

      - name: 7. Generate Dua for Goodness, Health, and Blessings
        run: node scripts/7_generate-dua-for-goodness-health-and-blessings.js

      - name: 7. Generate Dua for Protection from Unwanted Things
        run: node scripts/8_generate-dua-for-protection-from-unwanted-things.js

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
