name: Update Aggregated Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          submodules: true
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install || echo "No dependencies needed"

      - name: Generate Aggregated Data
        run: node scripts/1_generate-mapped-data.js

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
